In [1]:
from pathlib import Path
import pandas as pd

# Project paths
RAW_DIR = Path("../data/raw")

# Dataset paths
files = {
    "ipc_2001_2012": RAW_DIR / "dstrIPC_1.csv",
    "ipc_2013": RAW_DIR / "dstrIPC_2013.csv",
    "ipc_2014": RAW_DIR / "dstrIPC_1_2014.csv",
    "women_crime_2014": RAW_DIR / "District-wise_Crimes_committed_against_Women_2014.csv"
}

# Load datasets
datasets = {}

for name, path in files.items():
    datasets[name] = pd.read_csv(path)
    print(f"{name:20} -> {datasets[name].shape}")

print("\nAll datasets loaded successfully.")

ipc_2001_2012        -> (9017, 33)
ipc_2013             -> (823, 33)
ipc_2014             -> (838, 91)
women_crime_2014     -> (837, 19)

All datasets loaded successfully.

In [2]:
from pathlib import Path
import pandas as pd

# Primary datasets from the larger source collection
primary_files = {
    "ipc_2001_2013": RAW_DIR / "01_District_wise_crimes_committed_IPC_2001_2013.csv",
    "ipc_2014": RAW_DIR / "01_District_wise_crimes_committed_IPC_2014.csv",
    "women_2001_2013": RAW_DIR / "42_District_wise_crimes_committed_against_women_2001_2013.csv",
    "women_2014": RAW_DIR / "42_District_wise_crimes_committed_against_women_2014.csv"
}

primary_datasets = {}

for name, path in primary_files.items():
    df = pd.read_csv(path)
    primary_datasets[name] = df
    
    print(f"{name:20} -> {df.shape}")

ipc_2001_2013        -> (9385, 33)
ipc_2014             -> (802, 91)
women_2001_2013      -> (9385, 10)
women_2014           -> (801, 62)

In [3]:
for name, df in primary_datasets.items():
    print("\n" + "=" * 90)
    print(name)
    print("=" * 90)
    
    print("Shape:", df.shape)
    print("\nColumns:")
    
    for i, column in enumerate(df.columns, start=1):
        print(f"{i:2}. {column}")

==========================================================================================
ipc_2001_2013
==========================================================================================
Shape: (9385, 33)

Columns:
 1. State_UT
 2. District
 3. Year
 4. MURDER
 5. ATTEMPT TO MURDER
 6. CULPABLE HOMICIDE NOT AMOUNTING TO MURDER
 7. RAPE
 8. CUSTODIAL RAPE
 9. OTHER RAPE
10. KIDNAPPING & ABDUCTION
11. KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS
12. KIDNAPPING AND ABDUCTION OF OTHERS
13. DACOITY
14. PREPARATION AND ASSEMBLY FOR DACOITY
15. ROBBERY
16. BURGLARY
17. THEFT
18. AUTO THEFT
19. OTHER THEFT
20. RIOTS
21. CRIMINAL BREACH OF TRUST
22. CHEATING
23. COUNTERFIETING
24. ARSON
25. HURT/GREVIOUS HURT
26. DOWRY DEATHS
27. ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY
28. INSULT TO MODESTY OF WOMEN
29. CRUELTY BY HUSBAND OR HIS RELATIVES
30. IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES
31. CAUSING DEATH BY NEGLIGENCE
32. OTHER IPC CRIMES
33. TOTAL IPC CRIMES

==========================================================================================
ipc_2014
==========================================================================================
Shape: (802, 91)

Columns:
 1. State_UT
 2. District
 3. Year
 4. Murder
 5. Attempt to commit Murder
 6. Culpable Homicide not amounting to Murder
 7. Attempt to commit Culpable Homicide
 8. Rape
 9. Custodial Rape
10. Custodial_Gang Rape
11. Custodial_Other Rape
12. Rape other than Custodial
13. Rape_Gang Rape
14. Rape_Others
15. Attempt to commit Rape
16. Kidnapping & Abduction_Total
17. Kidnapping & Abduction
18. Kidnapping & Abduction in order to Murder
19. Kidnapping for Ransom
20. Kidnapping & Abduction of Women to compel her for marriage
21. Other Kidnapping
22. Dacoity
23. Dacoity with Murder
24. Other Dacoity
25. Making Preparation and Assembly for committing Dacoity
26. Robbery
27. Criminal Trespass/Burglary
28. Criminal Trespass or Burglary
29. House Trespass & House Breaking
30. Theft
31. Auto Theft
32. Other Thefts
33. Unlawful Assembly
34. Riots
35. Riots_Communal
36. Riots_Industrial
37. Riots_Political
38. Riots_Caste Conflict
39. Riots_SC/STs Vs Non-SCs/STs
40. Riots_Other Caste Conflict
41. Riots_Agrarian
42. Riots_Students
43. Riots_Sectarian
44. Riots_Others
45. Criminal Breach of Trust
46. Cheating
47. Forgery
48. Counterfeiting
49. Counterfeit Offences related to Counterfeit Coin
50. Counterfeiting Government Stamp
51. Counterfeit currency & Bank notes
52. Counterfeiting currency notes/Bank notes
53. Using forged or counterfeiting currency/Bank notes
54. Possession of forged or counterfeiting currency/Bank notes
55. Making or Possessing materials for forged currency/Bank notes
56. Making or Using documents resembling currency
57. Arson
58. Grievous Hurt
59. Hurt
60. Acid attack
61. Attempt to Acid Attack
62. Dowry Deaths
63. Assault on Women with intent to outrage her Modesty
64. Sexual Harassment
65. Assault or use of criminal force to women with intent to Disrobe
66. Voyeurism
67. Stalking
68. Other Assault on Women
69. Insult to the Modesty of Women
70. At Office premises
71. Other places related to work
72. In Public Transport system
73. Places other than 231, 232 & 233
74. Cruelty by Husband or his Relatives
75. Importation of Girls from Foreign Country
76. Causing Death by Negligence
77. Deaths due to negligent driving/act
78. Deaths due to Other Causes
79. Offences against State
80. Sedition
81. Other offences against State
82. Offences promoting enmity between different groups
83. Promoting enmity between different groups
84. Imputation, assertions prejudicial to national integration
85. Extortion
86. Disclosure of Identity of Victims
87. Incidence of Rash Driving
88. HumanTrafficking
89. Unnatural Offence
90. Other IPC crimes
91. Total Cognizable IPC crimes

==========================================================================================
women_2001_2013
==========================================================================================
Shape: (9385, 10)

Columns:
 1. State_UT
 2. District
 3. Year
 4. Rape
 5. Kidnapping and Abduction
 6. Dowry Deaths
 7. Assault on women with intent to outrage her modesty
 8. Insult to modesty of Women
 9. Cruelty by Husband or his Relatives
10. Importation of Girls

==========================================================================================
women_2014
==========================================================================================
Shape: (801, 62)

Columns:
 1. State_UT
 2. District
 3. Year
 4. Rape
 5. Custodial Rape
 6. Custodial_Gang Rape
 7. Custodial_Other Rape
 8. Rape other than Custodial
 9. Rape_Gang Rape
10. Rape_Others
11. Attempt to commit Rape
12. Kidnapping & Abduction_Total
13. Kidnaping & Abduction
14. Kidnaping & Abduction in order to Murder
15. Kidnapping for Ransom
16. Kidnapping & Abduction of Women to compel her for marriage
17. Kidnaping & Abduction_Others
18. Dowry Deaths
19. Assault on Women with intent to outrage her Modesty_Total
20. Sexual Harassment
21. Assault on women with intent to Disrobe
22. Voyeurism
23. Stalking
24. Others
25. Insult to the Modesty of Women_Total
26. At Office premises
27. In places related to work
28. In Public Transport system
29. In other Places
30. Cruelty by Husband or his Relatives
31. Importation of Girls from Foreign Country
32. Murder
33. Attempt to commit Murder
34. Culpable Homicide not amounting to Murder
35. Attempt to commit Culpable Homicide
36. Grievous Hurt
37. Hurt
38. Acid attack
39. Attempt to Acid Attack
40. Deaths caused with intent to cause miscarriage
41. Causing miscarriage without consent of women
42. Dacoity_Total
43. Dacoity with Murder
44. Other Dacoity
45. Robbery
46. Arson
47. HumanTrafficking
48. Abetment of Suicides of Women
49. UnNatural Offences
50. Other IPC Crimes
51. Dowry Prohibition Act, 1961
52. Indecent Representation of Women (P) Act, 1986
53. Commission of Sati Prevention Act, 1987
54. Protection of Women from Domestic Violence Act, 2005
55. Immoral Traffic Prevention Act
56. ITP Under Section 5
57. ITP Under Section 6
58. ITP Under Section 7
59. ITP Under Section 8
60. ITP Under Other Sections
61. Other SLL Crimes against Women
62. Total Crimes against Women

In [4]:
# Inspect State/UT values in the primary datasets

for name, df in primary_datasets.items():
    print("\n" + "=" * 80)
    print(name)
    print("=" * 80)
    
    print("Number of unique states/UTs:", df["State_UT"].nunique())
    print("\nState/UT values:")
    print(sorted(df["State_UT"].dropna().unique()))

================================================================================
ipc_2001_2013
================================================================================
Number of unique states/UTs: 35

State/UT values:
['Andaman & Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra & Nagar Haveli', 'Daman & Diu', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu & Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

================================================================================
ipc_2014
================================================================================
Number of unique states/UTs: 36

State/UT values:
['Andaman & Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra & Nagar Haveli', 'Daman & Diu', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu & Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

================================================================================
women_2001_2013
================================================================================
Number of unique states/UTs: 35

State/UT values:
['Andaman & Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra & Nagar Haveli', 'Daman & Diu', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu & Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

================================================================================
women_2014
================================================================================
Number of unique states/UTs: 36

State/UT values:
['Andaman & Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra & Nagar Haveli', 'Daman & Diu', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu & Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Lakshadweep', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']

In [5]:
# Check Maharashtra records and year coverage

for name, df in primary_datasets.items():
    maharashtra = df[
        df["State_UT"].astype(str).str.strip().str.upper() == "MAHARASHTRA"
    ]
    
    print("\n" + "=" * 80)
    print(name)
    print("=" * 80)
    
    print("Maharashtra rows:", len(maharashtra))
    
    if not maharashtra.empty:
        print("Years:", sorted(maharashtra["Year"].unique()))
        print("Districts:", maharashtra["District"].nunique())
        print("District names:")
        print(sorted(maharashtra["District"].dropna().unique()))

================================================================================
ipc_2001_2013
================================================================================
Maharashtra rows: 585
Years: [np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013)]
Districts: 46
District names:
['AHMEDNAGAR', 'AKOLA', 'AMRAVATI COMMR.', 'AMRAVATI RURAL', 'AURANGABAD COMMR.', 'AURANGABAD RURAL', 'BEED', 'BHANDARA', 'BULDHANA', 'CHANDRAPUR', 'DHULE', 'GADCHIROLI', 'GONDIA', 'HINGOLI', 'JALGAON', 'JALNA', 'KOLHAPUR', 'LATUR', 'MUMBAI', 'MUMBAI COMMR.', 'MUMBAI RLY.', 'NAGPUR COMMR.', 'NAGPUR RLY.', 'NAGPUR RURAL', 'NANDED', 'NANDURBAR', 'NASIK COMMR.', 'NASIK RURAL', 'NAVI MUMBAI', 'OSMANABAD', 'PARBHANI', 'PUNE COMMR.', 'PUNE RLY.', 'PUNE RURAL', 'RAIGAD', 'RATNAGIRI', 'SANGLI', 'SATARA', 'SINDHUDURG', 'SOLAPUR COMMR.', 'SOLAPUR RURAL', 'THANE COMMR.', 'THANE RURAL', 'WARDHA', 'WASHIM', 'YAVATMAL']

================================================================================
ipc_2014
================================================================================
Maharashtra rows: 46
Years: [np.int64(2014)]
Districts: 46
District names:
['Ahmednagar', 'Akola', 'Amravati Commr.', 'Amravati Rural', 'Aurangabad Commr.', 'Aurangabad Rural', 'Beed', 'Bhandara', 'Buldhana', 'Chandrapur', 'Dhule', 'Gadchiroli', 'Gondia', 'Hingoli', 'Jalgaon', 'Jalna', 'Kolhapur', 'Latur', 'Mumbai Commr.', 'Mumbai Railway', 'Nagpur Commr.', 'Nagpur Railway', 'Nagpur Rural', 'Nanded', 'Nandurbar', 'Nasik Commr.', 'Nasik Rural', 'Navi Mumbai', 'Osmanabad', 'Palghar', 'Parbhani', 'Pune Commr.', 'Pune Railway', 'Pune Rural', 'Raigad', 'Ratnagiri', 'Sangli', 'Satara', 'Sindhudurg', 'Solapur Commr.', 'Solapur Rural', 'Thane Commr.', 'Thane Rural', 'Wardha', 'Washim', 'Yavatmal']

================================================================================
women_2001_2013
================================================================================
Maharashtra rows: 585
Years: [np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013)]
Districts: 46
District names:
['AHMEDNAGAR', 'AKOLA', 'AMRAVATI COMMR.', 'AMRAVATI RURAL', 'AURANGABAD COMMR.', 'AURANGABAD RURAL', 'BEED', 'BHANDARA', 'BULDHANA', 'CHANDRAPUR', 'DHULE', 'GADCHIROLI', 'GONDIA', 'HINGOLI', 'JALGAON', 'JALNA', 'KOLHAPUR', 'LATUR', 'MUMBAI', 'MUMBAI COMMR.', 'MUMBAI RLY.', 'NAGPUR COMMR.', 'NAGPUR RLY.', 'NAGPUR RURAL', 'NANDED', 'NANDURBAR', 'NASIK COMMR.', 'NASIK RURAL', 'NAVI MUMBAI', 'OSMANABAD', 'PARBHANI', 'PUNE COMMR.', 'PUNE RLY.', 'PUNE RURAL', 'RAIGAD', 'RATNAGIRI', 'SANGLI', 'SATARA', 'SINDHUDURG', 'SOLAPUR COMMR.', 'SOLAPUR RURAL', 'THANE COMMR.', 'THANE RURAL', 'WARDHA', 'WASHIM', 'YAVATMAL']

================================================================================
women_2014
================================================================================
Maharashtra rows: 46
Years: [np.int64(2014)]
Districts: 46
District names:
['Ahmednagar', 'Akola', 'Amravati Commr.', 'Amravati Rural', 'Aurangabad Commr.', 'Aurangabad Rural', 'Beed', 'Bhandara', 'Buldhana', 'Chandrapur', 'Dhule', 'Gadchiroli', 'Gondia', 'Hingoli', 'Jalgaon', 'Jalna', 'Kolhapur', 'Latur', 'Mumbai Commr.', 'Mumbai Railway', 'Nagpur Commr.', 'Nagpur Railway', 'Nagpur Rural', 'Nanded', 'Nandurbar', 'Nasik Commr.', 'Nasik Rural', 'Navi Mumbai', 'Osmanabad', 'Palghar', 'Parbhani', 'Pune Commr.', 'Pune Railway', 'Pune Rural', 'Raigad', 'Ratnagiri', 'Sangli', 'Satara', 'Sindhudurg', 'Solapur Commr.', 'Solapur Rural', 'Thane Commr.', 'Thane Rural', 'Wardha', 'Washim', 'Yavatmal']

In [6]:
# Check whether State + District + Year uniquely identifies each record
# and whether the IPC and women-crime datasets have matching keys.

historical_ipc = primary_datasets["ipc_2001_2013"]
historical_women = primary_datasets["women_2001_2013"]

# Filter Maharashtra
ipc_mh = historical_ipc[
    historical_ipc["State_UT"].astype(str).str.strip().str.upper() == "MAHARASHTRA"
].copy()

women_mh = historical_women[
    historical_women["State_UT"].astype(str).str.strip().str.upper() == "MAHARASHTRA"
].copy()

# Define the join key
key_columns = ["State_UT", "District", "Year"]

# Check duplicate keys
ipc_duplicates = ipc_mh.duplicated(subset=key_columns).sum()
women_duplicates = women_mh.duplicated(subset=key_columns).sum()

print("IPC duplicate keys:", ipc_duplicates)
print("Women-crime duplicate keys:", women_duplicates)

# Compare keys between the two datasets
ipc_keys = set(map(tuple, ipc_mh[key_columns].itertuples(index=False, name=None)))
women_keys = set(map(tuple, women_mh[key_columns].itertuples(index=False, name=None)))

print("\nIPC unique keys:", len(ipc_keys))
print("Women-crime unique keys:", len(women_keys))

print("\nKeys present in IPC but missing in women-crime:", len(ipc_keys - women_keys))
print("Keys present in women-crime but missing in IPC:", len(women_keys - ipc_keys))

if ipc_keys - women_keys:
    print("\nExamples missing from women-crime:")
    print(list(ipc_keys - women_keys)[:10])

if women_keys - ipc_keys:
    print("\nExamples missing from IPC:")
    print(list(women_keys - ipc_keys)[:10])

IPC duplicate keys: 0
Women-crime duplicate keys: 0

IPC unique keys: 585
Women-crime unique keys: 585

Keys present in IPC but missing in women-crime: 0
Keys present in women-crime but missing in IPC: 0

In [7]:
# Compare Maharashtra district names between historical data and 2014

ipc_2014 = primary_datasets["ipc_2014"]
women_2014 = primary_datasets["women_2014"]

# Filter Maharashtra 2014
ipc_2014_mh = ipc_2014[
    ipc_2014["State_UT"].astype(str).str.strip().str.upper() == "MAHARASHTRA"
].copy()

women_2014_mh = women_2014[
    women_2014["State_UT"].astype(str).str.strip().str.upper() == "MAHARASHTRA"
].copy()

historical_districts = set(ipc_mh["District"].dropna().astype(str).str.strip())
ipc_2014_districts = set(ipc_2014_mh["District"].dropna().astype(str).str.strip())
women_2014_districts = set(women_2014_mh["District"].dropna().astype(str).str.strip())

print("Historical districts:", len(historical_districts))
print("IPC 2014 districts:", len(ipc_2014_districts))
print("Women 2014 districts:", len(women_2014_districts))

print("\n" + "=" * 80)
print("Historical → IPC 2014 differences")
print("=" * 80)

print("\nPresent historically but not in 2014:")
print(sorted(historical_districts - ipc_2014_districts))

print("\nPresent in 2014 but not historically:")
print(sorted(ipc_2014_districts - historical_districts))

Historical districts: 46
IPC 2014 districts: 46
Women 2014 districts: 46

================================================================================
Historical → IPC 2014 differences
================================================================================

Present historically but not in 2014:
['AHMEDNAGAR', 'AKOLA', 'AMRAVATI COMMR.', 'AMRAVATI RURAL', 'AURANGABAD COMMR.', 'AURANGABAD RURAL', 'BEED', 'BHANDARA', 'BULDHANA', 'CHANDRAPUR', 'DHULE', 'GADCHIROLI', 'GONDIA', 'HINGOLI', 'JALGAON', 'JALNA', 'KOLHAPUR', 'LATUR', 'MUMBAI', 'MUMBAI COMMR.', 'MUMBAI RLY.', 'NAGPUR COMMR.', 'NAGPUR RLY.', 'NAGPUR RURAL', 'NANDED', 'NANDURBAR', 'NASIK COMMR.', 'NASIK RURAL', 'NAVI MUMBAI', 'OSMANABAD', 'PARBHANI', 'PUNE COMMR.', 'PUNE RLY.', 'PUNE RURAL', 'RAIGAD', 'RATNAGIRI', 'SANGLI', 'SATARA', 'SINDHUDURG', 'SOLAPUR COMMR.', 'SOLAPUR RURAL', 'THANE COMMR.', 'THANE RURAL', 'WARDHA', 'WASHIM', 'YAVATMAL']

Present in 2014 but not historically:
['Ahmednagar', 'Akola', 'Amravati Commr.', 'Amravati Rural', 'Aurangabad Commr.', 'Aurangabad Rural', 'Beed', 'Bhandara', 'Buldhana', 'Chandrapur', 'Dhule', 'Gadchiroli', 'Gondia', 'Hingoli', 'Jalgaon', 'Jalna', 'Kolhapur', 'Latur', 'Mumbai Commr.', 'Mumbai Railway', 'Nagpur Commr.', 'Nagpur Railway', 'Nagpur Rural', 'Nanded', 'Nandurbar', 'Nasik Commr.', 'Nasik Rural', 'Navi Mumbai', 'Osmanabad', 'Palghar', 'Parbhani', 'Pune Commr.', 'Pune Railway', 'Pune Rural', 'Raigad', 'Ratnagiri', 'Sangli', 'Satara', 'Sindhudurg', 'Solapur Commr.', 'Solapur Rural', 'Thane Commr.', 'Thane Rural', 'Wardha', 'Washim', 'Yavatmal']

In [8]:
# Normalize district names to a common representation

def normalize_district_name(value):
    """
    Convert district names from different source formats
    into a common comparable representation.
    """
    if pd.isna(value):
        return None
    
    name = str(value).strip().upper()

    # Known naming differences between historical and 2014 data
    district_mapping = {
        "MUMBAI RLY.": "MUMBAI RAILWAY",
        "MUMBAI RAILWAY": "MUMBAI RAILWAY",
        
        "NAGPUR RLY.": "NAGPUR RAILWAY",
        "NAGPUR RAILWAY": "NAGPUR RAILWAY",
        
        "PUNE RLY.": "PUNE RAILWAY",
        "PUNE RAILWAY": "PUNE RAILWAY",
    }

    return district_mapping.get(name, name)


# Test normalization on all Maharashtra district names
historical_normalized = {
    normalize_district_name(x)
    for x in historical_districts
}

ipc_2014_normalized = {
    normalize_district_name(x)
    for x in ipc_2014_districts
}

print("Historical normalized districts:", len(historical_normalized))
print("2014 normalized districts:", len(ipc_2014_normalized))

print("\nPresent historically but not in 2014:")
print(sorted(historical_normalized - ipc_2014_normalized))

print("\nPresent in 2014 but not historically:")
print(sorted(ipc_2014_normalized - historical_normalized))

Historical normalized districts: 46
2014 normalized districts: 46

Present historically but not in 2014:
['MUMBAI']

Present in 2014 but not historically:
['PALGHAR']

In [9]:
# Prepare Maharashtra IPC and women-crime datasets for merging

# Copy the filtered Maharashtra datasets
ipc_historical_mh = ipc_mh.copy()
women_historical_mh = women_mh.copy()

# Normalize district names
ipc_historical_mh["District_Normalized"] = (
    ipc_historical_mh["District"].apply(normalize_district_name)
)

women_historical_mh["District_Normalized"] = (
    women_historical_mh["District"].apply(normalize_district_name)
)

# Create a consistent merge key
merge_columns = [
    "State_UT",
    "District_Normalized",
    "Year"
]

# Merge IPC + women-crime data
historical_merged = pd.merge(
    ipc_historical_mh,
    women_historical_mh,
    on=merge_columns,
    how="inner",
    suffixes=("_ipc", "_women"),
    validate="one_to_one"
)

print("IPC Maharashtra rows:", len(ipc_historical_mh))
print("Women-crime Maharashtra rows:", len(women_historical_mh))
print("Merged rows:", len(historical_merged))

print("\nMerged shape:", historical_merged.shape)

print("\nFirst 5 rows:")
display(historical_merged.head())

IPC Maharashtra rows: 585
Women-crime Maharashtra rows: 585
Merged rows: 585

Merged shape: (585, 42)

First 5 rows:

,State_UT,District_ipc,Year,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,KIDNAPPING & ABDUCTION,...,TOTAL IPC CRIMES,District_Normalized,District_women,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
0,Maharashtra,AHMEDNAGAR,2001,97,41,1,44,0,44,37,...,4391,AHMEDNAGAR,AHMEDNAGAR,44,25,0,74,2,496,0
1,Maharashtra,AKOLA,2001,64,41,0,15,0,15,15,...,4020,AKOLA,AKOLA,15,14,2,109,7,189,0
2,Maharashtra,AMRAVATI COMMR.,2001,44,29,3,23,0,23,27,...,2837,AMRAVATI COMMR.,AMRAVATI COMMR.,23,23,10,43,26,55,0
3,Maharashtra,AMRAVATI RURAL,2001,72,23,0,42,0,42,29,...,3655,AMRAVATI RURAL,AMRAVATI RURAL,42,25,4,99,38,92,0
4,Maharashtra,AURANGABAD COMMR.,2001,36,27,0,14,0,14,19,...,2351,AURANGABAD COMMR.,AURANGABAD COMMR.,14,14,4,33,12,102,0

In [10]:
# Inspect merged columns and identify duplicate crime measures

print("Total columns:", len(historical_merged.columns))

print("\nAll columns:")
for i, column in enumerate(historical_merged.columns, start=1):
    print(f"{i:2}. {column}")

print("\nPotential duplicate crime columns:")
duplicate_concepts = [
    ("RAPE", "Rape"),
    ("KIDNAPPING & ABDUCTION", "Kidnapping and Abduction"),
    ("DOWRY DEATHS", "Dowry Deaths"),
    ("ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY",
     "Assault on women with intent to outrage her modesty"),
    ("INSULT TO MODESTY OF WOMEN", "Insult to modesty of Women"),
    ("CRUELTY BY HUSBAND OR HIS RELATIVES",
     "Cruelty by Husband or his Relatives"),
    ("IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES",
     "Importation of Girls")
]

for ipc_col, women_col in duplicate_concepts:
    ipc_exists = ipc_col in historical_merged.columns
    women_exists = women_col in historical_merged.columns
    
    print(
        f"{ipc_col} ↔ {women_col} : "
        f"IPC={ipc_exists}, Women={women_exists}"
    )

Total columns: 42

All columns:
 1. State_UT
 2. District_ipc
 3. Year
 4. MURDER
 5. ATTEMPT TO MURDER
 6. CULPABLE HOMICIDE NOT AMOUNTING TO MURDER
 7. RAPE
 8. CUSTODIAL RAPE
 9. OTHER RAPE
10. KIDNAPPING & ABDUCTION
11. KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS
12. KIDNAPPING AND ABDUCTION OF OTHERS
13. DACOITY
14. PREPARATION AND ASSEMBLY FOR DACOITY
15. ROBBERY
16. BURGLARY
17. THEFT
18. AUTO THEFT
19. OTHER THEFT
20. RIOTS
21. CRIMINAL BREACH OF TRUST
22. CHEATING
23. COUNTERFIETING
24. ARSON
25. HURT/GREVIOUS HURT
26. DOWRY DEATHS
27. ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY
28. INSULT TO MODESTY OF WOMEN
29. CRUELTY BY HUSBAND OR HIS RELATIVES
30. IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES
31. CAUSING DEATH BY NEGLIGENCE
32. OTHER IPC CRIMES
33. TOTAL IPC CRIMES
34. District_Normalized
35. District_women
36. Rape
37. Kidnapping and Abduction
38. Dowry Deaths
39. Assault on women with intent to outrage her modesty
40. Insult to modesty of Women
41. Cruelty by Husband or his Relatives
42. Importation of Girls

Potential duplicate crime columns:
RAPE ↔ Rape : IPC=True, Women=True
KIDNAPPING & ABDUCTION ↔ Kidnapping and Abduction : IPC=True, Women=True
DOWRY DEATHS ↔ Dowry Deaths : IPC=True, Women=True
ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY ↔ Assault on women with intent to outrage her modesty : IPC=True, Women=True
INSULT TO MODESTY OF WOMEN ↔ Insult to modesty of Women : IPC=True, Women=True
CRUELTY BY HUSBAND OR HIS RELATIVES ↔ Cruelty by Husband or his Relatives : IPC=True, Women=True
IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES ↔ Importation of Girls : IPC=True, Women=True

In [11]:
# Compare duplicate crime measures between IPC and women-crime datasets

duplicate_pairs = [
    ("RAPE", "Rape"),
    ("KIDNAPPING & ABDUCTION", "Kidnapping and Abduction"),
    ("DOWRY DEATHS", "Dowry Deaths"),
    ("ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY",
     "Assault on women with intent to outrage her modesty"),
    ("INSULT TO MODESTY OF WOMEN", "Insult to modesty of Women"),
    ("CRUELTY BY HUSBAND OR HIS RELATIVES",
     "Cruelty by Husband or his Relatives"),
    ("IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES",
     "Importation of Girls")
]

for ipc_col, women_col in duplicate_pairs:
    ipc_values = pd.to_numeric(
        historical_merged[ipc_col], errors="coerce"
    )
    
    women_values = pd.to_numeric(
        historical_merged[women_col], errors="coerce"
    )

    equal = ipc_values.fillna(0).equals(women_values.fillna(0))
    difference_count = (ipc_values != women_values).sum()

    print(f"\n{ipc_col}")
    print(f"  ↳ {women_col}")
    print(f"  Values identical: {equal}")
    print(f"  Different rows: {difference_count}")

RAPE
  ↳ Rape
  Values identical: True
  Different rows: 0

KIDNAPPING & ABDUCTION
  ↳ Kidnapping and Abduction
  Values identical: False
  Different rows: 511

DOWRY DEATHS
  ↳ Dowry Deaths
  Values identical: True
  Different rows: 0

ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY
  ↳ Assault on women with intent to outrage her modesty
  Values identical: True
  Different rows: 0

INSULT TO MODESTY OF WOMEN
  ↳ Insult to modesty of Women
  Values identical: True
  Different rows: 0

CRUELTY BY HUSBAND OR HIS RELATIVES
  ↳ Cruelty by Husband or his Relatives
  Values identical: True
  Different rows: 0

IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES
  ↳ Importation of Girls
  Values identical: True
  Different rows: 0

In [12]:
# Investigate why the two kidnapping measures differ

kidnap_compare = historical_merged[
    [
        "District_ipc",
        "Year",
        "KIDNAPPING & ABDUCTION",
        "KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS",
        "KIDNAPPING AND ABDUCTION OF OTHERS",
        "Kidnapping and Abduction"
    ]
].copy()

# Calculate the difference
kidnap_compare["IPC_Total_minus_Women"] = (
    kidnap_compare["KIDNAPPING & ABDUCTION"]
    - kidnap_compare["Kidnapping and Abduction"]
)

print("Rows where kidnapping values differ:")
display(
    kidnap_compare[
        kidnap_compare["IPC_Total_minus_Women"] != 0
    ].head(20)
)

print("\nDifference statistics:")
print(
    kidnap_compare["IPC_Total_minus_Women"]
    .describe()
)

Rows where kidnapping values differ:

,District_ipc,Year,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,KIDNAPPING AND ABDUCTION OF OTHERS,Kidnapping and Abduction,IPC_Total_minus_Women
0,AHMEDNAGAR,2001,37,25,12,25,12
1,AKOLA,2001,15,14,1,14,1
2,AMRAVATI COMMR.,2001,27,23,4,23,4
3,AMRAVATI RURAL,2001,29,25,4,25,4
4,AURANGABAD COMMR.,2001,19,14,5,14,5
5,AURANGABAD RURAL,2001,16,6,10,6,10
6,BEED,2001,25,15,10,15,10
7,BHANDARA,2001,4,1,3,1,3
8,BULDHANA,2001,22,18,4,18,4
9,CHANDRAPUR,2001,10,7,3,7,3
11,GADCHIROLI,2001,7,6,1,6,1
13,HINGOLI,2001,9,8,1,8,1
14,JALGAON,2001,16,12,4,12,4
15,JALNA,2001,12,8,4,8,4
16,KOLHAPUR,2001,21,13,8,13,8
18,MUMBAI,2001,148,12,136,12,136
19,MUMBAI RLY.,2001,1,0,1,0,1
20,NAGPUR COMMR.,2001,64,51,13,51,13
22,NAGPUR RURAL,2001,23,16,7,16,7
23,NANDED,2001,41,36,5,36,5

Difference statistics:
count    585.000000
mean       8.570940
std       14.073882
min        0.000000
25%        2.000000
50%        4.000000
75%       10.000000
max      136.000000
Name: IPC_Total_minus_Women, dtype: float64

In [13]:
# Investigate why the two kidnapping measures differ

kidnap_compare = historical_merged[
    [
        "District_ipc",
        "Year",
        "KIDNAPPING & ABDUCTION",
        "KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS",
        "KIDNAPPING AND ABDUCTION OF OTHERS",
        "Kidnapping and Abduction"
    ]
].copy()

# Calculate the difference
kidnap_compare["IPC_Total_minus_Women"] = (
    kidnap_compare["KIDNAPPING & ABDUCTION"]
    - kidnap_compare["Kidnapping and Abduction"]
)

print("Rows where kidnapping values differ:")
display(
    kidnap_compare[
        kidnap_compare["IPC_Total_minus_Women"] != 0
    ].head(20)
)

print("\nDifference statistics:")
print(
    kidnap_compare["IPC_Total_minus_Women"]
    .describe()
)

Rows where kidnapping values differ:

,District_ipc,Year,KIDNAPPING & ABDUCTION,KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS,KIDNAPPING AND ABDUCTION OF OTHERS,Kidnapping and Abduction,IPC_Total_minus_Women
0,AHMEDNAGAR,2001,37,25,12,25,12
1,AKOLA,2001,15,14,1,14,1
2,AMRAVATI COMMR.,2001,27,23,4,23,4
3,AMRAVATI RURAL,2001,29,25,4,25,4
4,AURANGABAD COMMR.,2001,19,14,5,14,5
5,AURANGABAD RURAL,2001,16,6,10,6,10
6,BEED,2001,25,15,10,15,10
7,BHANDARA,2001,4,1,3,1,3
8,BULDHANA,2001,22,18,4,18,4
9,CHANDRAPUR,2001,10,7,3,7,3
11,GADCHIROLI,2001,7,6,1,6,1
13,HINGOLI,2001,9,8,1,8,1
14,JALGAON,2001,16,12,4,12,4
15,JALNA,2001,12,8,4,8,4
16,KOLHAPUR,2001,21,13,8,13,8
18,MUMBAI,2001,148,12,136,12,136
19,MUMBAI RLY.,2001,1,0,1,0,1
20,NAGPUR COMMR.,2001,64,51,13,51,13
22,NAGPUR RURAL,2001,23,16,7,16,7
23,NANDED,2001,41,36,5,36,5

Difference statistics:
count    585.000000
mean       8.570940
std       14.073882
min        0.000000
25%        2.000000
50%        4.000000
75%       10.000000
max      136.000000
Name: IPC_Total_minus_Women, dtype: float64

In [14]:
# Create a clean historical Maharashtra dataset
# Remove duplicate copies while preserving useful crime information.

historical_clean = historical_merged.copy()

# Rename important columns to clear, deployment-friendly names
historical_clean = historical_clean.rename(columns={
    "District_ipc": "District",
    "KIDNAPPING & ABDUCTION": "Total Kidnapping & Abduction",
    "KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS": "Kidnapping & Abduction of Women",
    "KIDNAPPING AND ABDUCTION OF OTHERS": "Kidnapping & Abduction of Others",
})

# Remove duplicate metadata columns
historical_clean = historical_clean.drop(
    columns=[
        "District_Normalized",
        "District_women",
        "Rape",
        "Kidnapping and Abduction",
        "Dowry Deaths",
        "Assault on women with intent to outrage her modesty",
        "Insult to modesty of Women",
        "Cruelty by Husband or his Relatives",
        "Importation of Girls"
    ]
)

print("Clean historical shape:", historical_clean.shape)

print("\nColumns:")
for i, column in enumerate(historical_clean.columns, start=1):
    print(f"{i:2}. {column}")

print("\nFirst 5 rows:")
display(historical_clean.head())

Clean historical shape: (585, 33)

Columns:
 1. State_UT
 2. District
 3. Year
 4. MURDER
 5. ATTEMPT TO MURDER
 6. CULPABLE HOMICIDE NOT AMOUNTING TO MURDER
 7. RAPE
 8. CUSTODIAL RAPE
 9. OTHER RAPE
10. Total Kidnapping & Abduction
11. Kidnapping & Abduction of Women
12. Kidnapping & Abduction of Others
13. DACOITY
14. PREPARATION AND ASSEMBLY FOR DACOITY
15. ROBBERY
16. BURGLARY
17. THEFT
18. AUTO THEFT
19. OTHER THEFT
20. RIOTS
21. CRIMINAL BREACH OF TRUST
22. CHEATING
23. COUNTERFIETING
24. ARSON
25. HURT/GREVIOUS HURT
26. DOWRY DEATHS
27. ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY
28. INSULT TO MODESTY OF WOMEN
29. CRUELTY BY HUSBAND OR HIS RELATIVES
30. IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES
31. CAUSING DEATH BY NEGLIGENCE
32. OTHER IPC CRIMES
33. TOTAL IPC CRIMES

First 5 rows:

,State_UT,District,Year,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,Total Kidnapping & Abduction,...,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
0,Maharashtra,AHMEDNAGAR,2001,97,41,1,44,0,44,37,...,44,575,0,74,2,496,0,479,975,4391
1,Maharashtra,AKOLA,2001,64,41,0,15,0,15,15,...,48,836,2,109,7,189,0,116,1306,4020
2,Maharashtra,AMRAVATI COMMR.,2001,44,29,3,23,0,23,27,...,15,429,10,43,26,55,0,60,796,2837
3,Maharashtra,AMRAVATI RURAL,2001,72,23,0,42,0,42,29,...,23,884,4,99,38,92,0,126,640,3655
4,Maharashtra,AURANGABAD COMMR.,2001,36,27,0,14,0,14,19,...,3,371,4,33,12,102,0,109,569,2351

In [17]:
# ============================================================
# STEP 2 — Prepare Maharashtra 2014 data (CORRECTED)
# ============================================================

# Filter Maharashtra
ipc_2014_mh = ipc_2014[
    ipc_2014["State_UT"].astype(str).str.strip().str.upper() == "MAHARASHTRA"
].copy()

women_2014_mh = women_2014[
    women_2014["State_UT"].astype(str).str.strip().str.upper() == "MAHARASHTRA"
].copy()

# Normalize districts
ipc_2014_mh["District_Normalized"] = (
    ipc_2014_mh["District"].apply(normalize_district_name)
)

women_2014_mh["District_Normalized"] = (
    women_2014_mh["District"].apply(normalize_district_name)
)

# ------------------------------------------------------------
# Rename 2014 IPC columns to historical/common names
# ------------------------------------------------------------

ipc_2014_mh = ipc_2014_mh.rename(columns={
    "Murder": "MURDER",
    "Attempt to commit Murder": "ATTEMPT TO MURDER",
    "Culpable Homicide not amounting to Murder":
        "CULPABLE HOMICIDE NOT AMOUNTING TO MURDER",

    "Rape": "RAPE",
    "Custodial Rape": "CUSTODIAL RAPE",
    "Rape other than Custodial": "OTHER RAPE",

    "Kidnapping & Abduction_Total":
        "Total Kidnapping & Abduction",
    "Kidnapping & Abduction":
        "Kidnapping & Abduction of Women",

    "Dacoity": "DACOITY",
    "Making Preparation and Assembly for committing Dacoity":
        "PREPARATION AND ASSEMBLY FOR DACOITY",

    "Robbery": "ROBBERY",
    "Criminal Trespass/Burglary": "BURGLARY",
    "Theft": "THEFT",
    "Auto Theft": "AUTO THEFT",
    "Other Thefts": "OTHER THEFT",

    "Riots": "RIOTS",
    "Criminal Breach of Trust": "CRIMINAL BREACH OF TRUST",
    "Cheating": "CHEATING",
    "Counterfeiting": "COUNTERFIETING",
    "Arson": "ARSON",

    "Dowry Deaths": "DOWRY DEATHS",

    "Assault on Women with intent to outrage her Modesty":
        "ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY",

    "Insult to the Modesty of Women":
        "INSULT TO MODESTY OF WOMEN",

    "Cruelty by Husband or his Relatives":
        "CRUELTY BY HUSBAND OR HIS RELATIVES",

    "Importation of Girls from Foreign Country":
        "IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES",

    "Causing Death by Negligence":
        "CAUSING DEATH BY NEGLIGENCE",

    "Other IPC crimes": "OTHER IPC CRIMES",
    "Total Cognizable IPC crimes": "TOTAL IPC CRIMES"
})

# ------------------------------------------------------------
# Create "Kidnapping & Abduction of Others"
# ------------------------------------------------------------

ipc_2014_mh["Kidnapping & Abduction of Others"] = (
    ipc_2014_mh["Total Kidnapping & Abduction"]
    - ipc_2014_mh["Kidnapping & Abduction of Women"]
)

# ------------------------------------------------------------
# Create historical-compatible Hurt/Grievous Hurt
# ------------------------------------------------------------

ipc_2014_mh["HURT/GREVIOUS HURT"] = (
    ipc_2014_mh["Grievous Hurt"]
    + ipc_2014_mh["Hurt"]
)

# ------------------------------------------------------------
# Check required common columns
# ------------------------------------------------------------

common_columns = list(historical_clean.columns)

missing_2014_columns = [
    col for col in common_columns
    if col not in ipc_2014_mh.columns
]

print("Missing common columns in 2014 IPC:")
print(missing_2014_columns)

# ------------------------------------------------------------
# Select exact historical schema
# ------------------------------------------------------------

ipc_2014_common = ipc_2014_mh[common_columns].copy()

print("\n2014 IPC common-schema shape:", ipc_2014_common.shape)

print("\nFirst 5 rows:")
display(ipc_2014_common.head())

Missing common columns in 2014 IPC:
[]

2014 IPC common-schema shape: (46, 33)

First 5 rows:

,State_UT,District,Year,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,Total Kidnapping & Abduction,...,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
419,Maharashtra,Ahmednagar,2014,109,74,6,103,0,103,121,...,46,398,13,269,8,264,0,736,1113,6957
420,Maharashtra,Akola,2014,52,50,3,52,0,52,42,...,34,242,5,219,20,136,0,141,1724,4433
421,Maharashtra,Amravati Commr.,2014,27,49,2,27,0,27,36,...,16,138,1,132,12,108,0,82,975,3338
422,Maharashtra,Amravati Rural,2014,51,63,5,103,0,103,76,...,70,538,8,415,17,213,0,237,3196,6948
423,Maharashtra,Aurangabad Commr.,2014,35,54,0,27,0,27,63,...,35,142,2,227,5,164,0,183,851,4821

In [18]:
# ============================================================
# STEP 2 — Prepare Maharashtra 2014 data
# ============================================================

# Filter Maharashtra
ipc_2014_mh = ipc_2014[
    ipc_2014["State_UT"].astype(str).str.strip().str.upper() == "MAHARASHTRA"
].copy()

women_2014_mh = women_2014[
    women_2014["State_UT"].astype(str).str.strip().str.upper() == "MAHARASHTRA"
].copy()


# ------------------------------------------------------------
# Normalize district names
# ------------------------------------------------------------

ipc_2014_mh["District_Normalized"] = (
    ipc_2014_mh["District"].apply(normalize_district_name)
)

women_2014_mh["District_Normalized"] = (
    women_2014_mh["District"].apply(normalize_district_name)
)


# ------------------------------------------------------------
# Rename 2014 IPC columns to historical schema
# ------------------------------------------------------------

ipc_2014_mh = ipc_2014_mh.rename(columns={
    "Murder": "MURDER",
    "Attempt to commit Murder": "ATTEMPT TO MURDER",
    "Culpable Homicide not amounting to Murder":
        "CULPABLE HOMICIDE NOT AMOUNTING TO MURDER",

    "Rape": "RAPE",
    "Custodial Rape": "CUSTODIAL RAPE",
    "Rape other than Custodial": "OTHER RAPE",

    "Kidnapping & Abduction_Total":
        "Total Kidnapping & Abduction",

    "Kidnapping & Abduction":
        "Kidnapping & Abduction of Women",

    "Dacoity":
        "DACOITY",

    "Making Preparation and Assembly for committing Dacoity":
        "PREPARATION AND ASSEMBLY FOR DACOITY",

    "Robbery":
        "ROBBERY",

    "Criminal Trespass/Burglary":
        "BURGLARY",

    "Theft":
        "THEFT",

    "Auto Theft":
        "AUTO THEFT",

    "Other Thefts":
        "OTHER THEFT",

    "Riots":
        "RIOTS",

    "Criminal Breach of Trust":
        "CRIMINAL BREACH OF TRUST",

    "Cheating":
        "CHEATING",

    "Counterfeiting":
        "COUNTERFIETING",

    "Arson":
        "ARSON",

    "Dowry Deaths":
        "DOWRY DEATHS",

    "Assault on Women with intent to outrage her Modesty":
        "ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY",

    "Insult to the Modesty of Women":
        "INSULT TO MODESTY OF WOMEN",

    "Cruelty by Husband or his Relatives":
        "CRUELTY BY HUSBAND OR HIS RELATIVES",

    "Importation of Girls from Foreign Country":
        "IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES",

    "Causing Death by Negligence":
        "CAUSING DEATH BY NEGLIGENCE",

    "Other IPC crimes":
        "OTHER IPC CRIMES",

    "Total Cognizable IPC crimes":
        "TOTAL IPC CRIMES"
})


# ------------------------------------------------------------
# Derive categories that don't have direct historical names
# ------------------------------------------------------------

# Total kidnapping = women + others
ipc_2014_mh["Kidnapping & Abduction of Others"] = (
    ipc_2014_mh["Total Kidnapping & Abduction"]
    - ipc_2014_mh["Kidnapping & Abduction of Women"]
)


# Historical "HURT/GREVIOUS HURT" corresponds to the
# combination of the separate 2014 Hurt + Grievous Hurt fields.

ipc_2014_mh["HURT/GREVIOUS HURT"] = (
    pd.to_numeric(ipc_2014_mh["Hurt"], errors="coerce").fillna(0)
    +
    pd.to_numeric(ipc_2014_mh["Grievous Hurt"], errors="coerce").fillna(0)
)


# ------------------------------------------------------------
# Build common schema
# ------------------------------------------------------------

common_columns = list(historical_clean.columns)

missing_2014_columns = [
    column
    for column in common_columns
    if column not in ipc_2014_mh.columns
]

print("Missing common columns in 2014 IPC:")
print(missing_2014_columns)


# Select only the common historical features
ipc_2014_common = ipc_2014_mh[common_columns].copy()


# ------------------------------------------------------------
# Basic validation
# ------------------------------------------------------------

print("\n2014 IPC common-schema shape:", ipc_2014_common.shape)

print("Expected rows: 46")
print("Actual rows:", len(ipc_2014_common))

print("\nExpected columns:", len(common_columns))
print("Actual columns:", len(ipc_2014_common.columns))

print("\nYears:")
print(ipc_2014_common["Year"].unique())

print("\nMissing values:")
print(ipc_2014_common.isna().sum()[lambda x: x > 0])

print("\nFirst 5 rows:")
display(ipc_2014_common.head())

Missing common columns in 2014 IPC:
[]

2014 IPC common-schema shape: (46, 33)
Expected rows: 46
Actual rows: 46

Expected columns: 33
Actual columns: 33

Years:
[2014]

Missing values:
Series([], dtype: int64)

First 5 rows:

,State_UT,District,Year,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,Total Kidnapping & Abduction,...,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
419,Maharashtra,Ahmednagar,2014,109,74,6,103,0,103,121,...,46,398,13,269,8,264,0,736,1113,6957
420,Maharashtra,Akola,2014,52,50,3,52,0,52,42,...,34,242,5,219,20,136,0,141,1724,4433
421,Maharashtra,Amravati Commr.,2014,27,49,2,27,0,27,36,...,16,138,1,132,12,108,0,82,975,3338
422,Maharashtra,Amravati Rural,2014,51,63,5,103,0,103,76,...,70,538,8,415,17,213,0,237,3196,6948
423,Maharashtra,Aurangabad Commr.,2014,35,54,0,27,0,27,63,...,35,142,2,227,5,164,0,183,851,4821

In [20]:
# ============================================================
# STEP 3 — Validate 2014 IPC vs Women-Crime data
# ============================================================

# Reset indexes so both datasets can be compared row-by-row
ipc_check = ipc_2014_mh.reset_index(drop=True)
women_check = women_2014_mh.reset_index(drop=True)

women_validation_pairs = [
    ("RAPE", "RAPE"),
    ("Total Kidnapping & Abduction", "Total Kidnapping & Abduction"),
    ("Kidnapping & Abduction of Women",
     "Kidnapping & Abduction of Women"),
    ("DOWRY DEATHS", "DOWRY DEATHS"),
    ("ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY",
     "ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY"),
    ("INSULT TO MODESTY OF WOMEN",
     "INSULT TO MODESTY OF WOMEN"),
    ("CRUELTY BY HUSBAND OR HIS RELATIVES",
     "CRUELTY BY HUSBAND OR HIS RELATIVES"),
    ("IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES",
     "IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES")
]

print("2014 IPC vs Women-crime comparison\n")

for ipc_col, women_col in women_validation_pairs:

    ipc_values = pd.to_numeric(
        ipc_check[ipc_col],
        errors="coerce"
    ).fillna(0).reset_index(drop=True)

    women_values = pd.to_numeric(
        women_check[women_col],
        errors="coerce"
    ).fillna(0).reset_index(drop=True)

    differences = (ipc_values.to_numpy() != women_values.to_numpy()).sum()

    print(f"{ipc_col:<60} Differences: {differences}")

2014 IPC vs Women-crime comparison

RAPE                                                         Differences: 0
Total Kidnapping & Abduction                                 Differences: 44
Kidnapping & Abduction of Women                              Differences: 35
DOWRY DEATHS                                                 Differences: 0
ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY          Differences: 0
INSULT TO MODESTY OF WOMEN                                   Differences: 0
CRUELTY BY HUSBAND OR HIS RELATIVES                          Differences: 0
IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES                  Differences: 0

In [21]:
# ============================================================
# STEP 4 — BUILD FINAL 2001–2014 MAHARASHTRA DATASET
# ============================================================

# ------------------------------------------------------------
# 1. Prepare historical data
# ------------------------------------------------------------

historical_final = historical_clean.copy()


# ------------------------------------------------------------
# 2. Prepare 2014 data
# ------------------------------------------------------------

final_2014 = ipc_2014_common.copy()


# ------------------------------------------------------------
# 3. Standardize district names
# ------------------------------------------------------------

historical_final["District"] = (
    historical_final["District"]
    .astype(str)
    .str.strip()
    .str.upper()
)

final_2014["District"] = (
    final_2014["District"]
    .apply(normalize_district_name)
)


# ------------------------------------------------------------
# 4. Standardize State and Year
# ------------------------------------------------------------

historical_final["State_UT"] = (
    historical_final["State_UT"]
    .astype(str)
    .str.strip()
)

final_2014["State_UT"] = (
    final_2014["State_UT"]
    .astype(str)
    .str.strip()
)

historical_final["Year"] = pd.to_numeric(
    historical_final["Year"],
    errors="coerce"
).astype(int)

final_2014["Year"] = pd.to_numeric(
    final_2014["Year"],
    errors="coerce"
).astype(int)


# ------------------------------------------------------------
# 5. Ensure identical column order
# ------------------------------------------------------------

final_2014 = final_2014[
    historical_final.columns
]


# ------------------------------------------------------------
# 6. Combine 2001–2013 + 2014
# ------------------------------------------------------------

maharashtra_crime_2001_2014 = pd.concat(
    [
        historical_final,
        final_2014
    ],
    ignore_index=True
)


# ------------------------------------------------------------
# 7. Sort chronologically
# ------------------------------------------------------------

maharashtra_crime_2001_2014 = (
    maharashtra_crime_2001_2014
    .sort_values(
        ["Year", "District"]
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 8. Final validation
# ------------------------------------------------------------

print("=" * 70)
print("FINAL DATASET VALIDATION")
print("=" * 70)

print("\nShape:")
print(maharashtra_crime_2001_2014.shape)

print("\nExpected:")
print("Rows    :", 585 + 46)
print("Columns :", len(historical_clean.columns))

print("\nActual:")
print("Rows    :", len(maharashtra_crime_2001_2014))
print("Columns :", len(maharashtra_crime_2001_2014.columns))

print("\nYear coverage:")
print(
    maharashtra_crime_2001_2014["Year"]
    .value_counts()
    .sort_index()
)

print("\nDistrict count:")
print(
    maharashtra_crime_2001_2014["District"].nunique()
)

print("\nDuplicate District-Year records:")
print(
    maharashtra_crime_2001_2014
    .duplicated(
        subset=["District", "Year"]
    )
    .sum()
)

print("\nMissing values:")
missing_final = maharashtra_crime_2001_2014.isna().sum()
print(
    missing_final[missing_final > 0]
)

print("\nNegative values:")
crime_columns = [
    c for c in maharashtra_crime_2001_2014.columns
    if c not in ["State_UT", "District", "Year"]
]

negative_values = (
    maharashtra_crime_2001_2014[crime_columns]
    .select_dtypes(include="number")
    .lt(0)
    .sum()
)

print(
    negative_values[negative_values > 0]
)

print("\nFirst 5 rows:")
display(
    maharashtra_crime_2001_2014.head()
)

print("\nLast 5 rows:")
display(
    maharashtra_crime_2001_2014.tail()
)

======================================================================
FINAL DATASET VALIDATION
======================================================================

Shape:
(631, 33)

Expected:
Rows    : 631
Columns : 33

Actual:
Rows    : 631
Columns : 33

Year coverage:
Year
2001    45
2002    45
2003    45
2004    45
2005    45
2006    45
2007    45
2008    45
2009    45
2010    45
2011    45
2012    45
2013    45
2014    46
Name: count, dtype: int64

District count:
50

Duplicate District-Year records:
0

Missing values:
Series([], dtype: int64)

Negative values:
Series([], dtype: int64)

First 5 rows:

,State_UT,District,Year,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,Total Kidnapping & Abduction,...,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
0,Maharashtra,AHMEDNAGAR,2001,97,41,1,44,0,44,37,...,44,575,0,74,2,496,0,479,975,4391
1,Maharashtra,AKOLA,2001,64,41,0,15,0,15,15,...,48,836,2,109,7,189,0,116,1306,4020
2,Maharashtra,AMRAVATI COMMR.,2001,44,29,3,23,0,23,27,...,15,429,10,43,26,55,0,60,796,2837
3,Maharashtra,AMRAVATI RURAL,2001,72,23,0,42,0,42,29,...,23,884,4,99,38,92,0,126,640,3655
4,Maharashtra,AURANGABAD COMMR.,2001,36,27,0,14,0,14,19,...,3,371,4,33,12,102,0,109,569,2351

Last 5 rows:

,State_UT,District,Year,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,Total Kidnapping & Abduction,...,ARSON,HURT/GREVIOUS HURT,DOWRY DEATHS,ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY,INSULT TO MODESTY OF WOMEN,CRUELTY BY HUSBAND OR HIS RELATIVES,IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES,CAUSING DEATH BY NEGLIGENCE,OTHER IPC CRIMES,TOTAL IPC CRIMES
626,Maharashtra,THANE COMMR.,2014,117,122,2,215,0,215,435,...,38,1142,13,559,73,351,0,306,1931,13227
627,Maharashtra,THANE RURAL,2014,51,23,11,75,0,75,71,...,26,214,3,165,39,103,0,216,761,3641
628,Maharashtra,WARDHA,2014,35,64,8,62,0,62,37,...,19,218,1,192,8,98,0,166,1620,3687
629,Maharashtra,WASHIM,2014,31,62,5,33,0,33,32,...,26,142,5,178,11,113,0,132,867,2579
630,Maharashtra,YAVATMAL,2014,75,98,5,108,0,108,157,...,65,474,12,466,504,301,0,243,4070,9951

In [22]:
# ============================================================
# STEP 5 — SAVE CLEAN PROCESSED DATA
# ============================================================

PROCESSED_DIR = Path("../data/processed")
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

output_path = (
    PROCESSED_DIR /
    "maharashtra_crime_2001_2014_clean.csv"
)

maharashtra_crime_2001_2014.to_csv(
    output_path,
    index=False
)

print("Saved successfully:")
print(output_path.resolve())

print("\nFile shape:")
print(maharashtra_crime_2001_2014.shape)

Saved successfully:
D:\B-Tech\Project\Aditya\ml\data\processed\maharashtra_crime_2001_2014_clean.csv

File shape:
(631, 33)

In [23]:
# ============================================================
# STEP 6 — FEATURE ENGINEERING FOR ML
# ============================================================

import numpy as np

df = maharashtra_crime_2001_2014.copy()

# ------------------------------------------------------------
# 1. Identify numeric crime columns
# ------------------------------------------------------------

id_columns = ["State_UT", "District", "Year"]

crime_columns = [
    c for c in df.columns
    if c not in id_columns
]

df[crime_columns] = df[crime_columns].apply(
    pd.to_numeric,
    errors="coerce"
).fillna(0)


# ------------------------------------------------------------
# 2. Women-safety aggregate features
# ------------------------------------------------------------

df["WOMEN_CRIME_TOTAL"] = (
    df["RAPE"]
    + df["Kidnapping & Abduction of Women"]
    + df["DOWRY DEATHS"]
    + df["ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY"]
    + df["INSULT TO MODESTY OF WOMEN"]
    + df["CRUELTY BY HUSBAND OR HIS RELATIVES"]
    + df["IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES"]
)


# ------------------------------------------------------------
# 3. Violent-crime aggregate
# ------------------------------------------------------------

df["VIOLENT_CRIME_TOTAL"] = (
    df["MURDER"]
    + df["ATTEMPT TO MURDER"]
    + df["CULPABLE HOMICIDE NOT AMOUNTING TO MURDER"]
    + df["RAPE"]
    + df["Total Kidnapping & Abduction"]
    + df["ROBBERY"]
    + df["RIOTS"]
    + df["HURT/GREVIOUS HURT"]
)


# ------------------------------------------------------------
# 4. Property-crime aggregate
# ------------------------------------------------------------

df["PROPERTY_CRIME_TOTAL"] = (
    df["BURGLARY"]
    + df["THEFT"]
    + df["AUTO THEFT"]
    + df["OTHER THEFT"]
)


# ------------------------------------------------------------
# 5. Create previous-year features
# ------------------------------------------------------------

df = df.sort_values(
    ["District", "Year"]
).reset_index(drop=True)

group = df.groupby("District", group_keys=False)

df["IPC_TOTAL_LAG_1"] = group["TOTAL IPC CRIMES"].shift(1)

df["WOMEN_CRIME_LAG_1"] = group["WOMEN_CRIME_TOTAL"].shift(1)

df["VIOLENT_CRIME_LAG_1"] = group["VIOLENT_CRIME_TOTAL"].shift(1)


# ------------------------------------------------------------
# 6. Rolling historical averages
#    IMPORTANT: shift first to avoid data leakage
# ------------------------------------------------------------

df["IPC_ROLLING_MEAN_3"] = (
    group["TOTAL IPC CRIMES"]
    .transform(
        lambda x: x.shift(1).rolling(3, min_periods=1).mean()
    )
)

df["WOMEN_ROLLING_MEAN_3"] = (
    group["WOMEN_CRIME_TOTAL"]
    .transform(
        lambda x: x.shift(1).rolling(3, min_periods=1).mean()
    )
)


# ------------------------------------------------------------
# 7. Year-over-year IPC trend
# ------------------------------------------------------------

df["IPC_YEARLY_CHANGE"] = (
    df["TOTAL IPC CRIMES"]
    - df["IPC_TOTAL_LAG_1"]
)

df["WOMEN_YEARLY_CHANGE"] = (
    df["WOMEN_CRIME_TOTAL"]
    - df["WOMEN_CRIME_LAG_1"]
)


# ------------------------------------------------------------
# 8. Create NEXT-YEAR prediction targets
# ------------------------------------------------------------

df["TARGET_NEXT_YEAR_IPC"] = (
    group["TOTAL IPC CRIMES"].shift(-1)
)

df["TARGET_NEXT_YEAR_WOMEN_CRIME"] = (
    group["WOMEN_CRIME_TOTAL"].shift(-1)
)


# ------------------------------------------------------------
# 9. Remove rows where next-year target doesn't exist
# ------------------------------------------------------------

modeling_df = df.dropna(
    subset=[
        "TARGET_NEXT_YEAR_IPC",
        "TARGET_NEXT_YEAR_WOMEN_CRIME"
    ]
).copy()


# ------------------------------------------------------------
# 10. Final validation
# ------------------------------------------------------------

print("=" * 70)
print("ML DATASET")
print("=" * 70)

print("\nOriginal rows:", len(df))
print("Modeling rows:", len(modeling_df))
print("Feature columns:", len(modeling_df.columns))

print("\nYear range:")
print(
    modeling_df["Year"].min(),
    "→",
    modeling_df["Year"].max()
)

print("\nTarget availability:")
print(
    modeling_df[
        [
            "TARGET_NEXT_YEAR_IPC",
            "TARGET_NEXT_YEAR_WOMEN_CRIME"
        ]
    ].isna().sum()
)

print("\nMissing values:")
missing = modeling_df.isna().sum()
print(missing[missing > 0])

print("\nFeature preview:")
display(
    modeling_df[
        [
            "District",
            "Year",
            "TOTAL IPC CRIMES",
            "WOMEN_CRIME_TOTAL",
            "VIOLENT_CRIME_TOTAL",
            "PROPERTY_CRIME_TOTAL",
            "IPC_TOTAL_LAG_1",
            "IPC_ROLLING_MEAN_3",
            "TARGET_NEXT_YEAR_IPC",
            "TARGET_NEXT_YEAR_WOMEN_CRIME"
        ]
    ].head(15)
)

======================================================================
ML DATASET
======================================================================

Original rows: 631
Modeling rows: 581
Feature columns: 45

Year range:
2001 → 2013

Target availability:
TARGET_NEXT_YEAR_IPC            0
TARGET_NEXT_YEAR_WOMEN_CRIME    0
dtype: int64

Missing values:
IPC_TOTAL_LAG_1         46
WOMEN_CRIME_LAG_1       46
VIOLENT_CRIME_LAG_1     46
IPC_ROLLING_MEAN_3      46
WOMEN_ROLLING_MEAN_3    46
IPC_YEARLY_CHANGE       46
WOMEN_YEARLY_CHANGE     46
dtype: int64

Feature preview:

,District,Year,TOTAL IPC CRIMES,WOMEN_CRIME_TOTAL,VIOLENT_CRIME_TOTAL,PROPERTY_CRIME_TOTAL,IPC_TOTAL_LAG_1,IPC_ROLLING_MEAN_3,TARGET_NEXT_YEAR_IPC,TARGET_NEXT_YEAR_WOMEN_CRIME
0,AHMEDNAGAR,2001,4391,641,1165,1742,NaN,NaN,4506.0,428.0
1,AHMEDNAGAR,2002,4506,428,1261,2034,4391.0,4391.000000,4251.0,413.0
2,AHMEDNAGAR,2003,4251,413,1143,1874,4506.0,4448.500000,4738.0,404.0
3,AHMEDNAGAR,2004,4738,404,1122,2247,4251.0,4382.666667,5241.0,510.0
4,AHMEDNAGAR,2005,5241,510,1296,2442,4738.0,4498.333333,6173.0,686.0
5,AHMEDNAGAR,2006,6173,686,1329,3082,5241.0,4743.333333,6753.0,702.0
6,AHMEDNAGAR,2007,6753,702,1542,3146,6173.0,5384.000000,7070.0,748.0
7,AHMEDNAGAR,2008,7070,748,1739,3502,6753.0,6055.666667,6530.0,743.0
8,AHMEDNAGAR,2009,6530,743,1589,3277,7070.0,6665.333333,7215.0,832.0
9,AHMEDNAGAR,2010,7215,832,1756,3613,6530.0,6784.333333,7648.0,1011.0
10,AHMEDNAGAR,2011,7648,1011,1997,3870,7215.0,6938.333333,7246.0,857.0
11,AHMEDNAGAR,2012,7246,857,1963,3229,7648.0,7131.000000,7934.0,843.0
12,AHMEDNAGAR,2013,7934,843,2069,3758,7246.0,7369.666667,6957.0,687.0
14,AKOLA,2001,4020,336,1111,1768,NaN,NaN,3886.0,285.0
15,AKOLA,2002,3886,285,1104,1772,4020.0,4020.000000,3900.0,284.0

In [24]:
# ============================================================
# STEP 7 — CHECK YEAR/DISTRICT CONTINUITY
# ============================================================

# Show number of records by year
print("Rows by year:")
print(
    df.groupby("Year")
      .size()
      .sort_index()
)

print("\n" + "=" * 70)

# Check which district-year combinations are missing
years = sorted(df["Year"].unique())

expected_years = set(range(2001, 2015))

district_year_check = (
    df.groupby("District")["Year"]
      .apply(set)
)

print("District continuity problems:\n")

for district, available_years in district_year_check.items():

    missing_years = sorted(
        expected_years - available_years
    )

    if missing_years:
        print(
            f"{district}: missing {missing_years}"
        )

print("\n" + "=" * 70)

# Check how many rows have a valid next-year target
print("Rows with next-year target:",
      df["TARGET_NEXT_YEAR_IPC"].notna().sum())

print("Rows without next-year target:",
      df["TARGET_NEXT_YEAR_IPC"].isna().sum())

print("\nRows without target:")
display(
    df[
        df["TARGET_NEXT_YEAR_IPC"].isna()
    ][
        ["District", "Year"]
    ].sort_values(["Year", "District"])
)

Rows by year:
Year
2001    45
2002    45
2003    45
2004    45
2005    45
2006    45
2007    45
2008    45
2009    45
2010    45
2011    45
2012    45
2013    45
2014    46
dtype: int64

======================================================================
District continuity problems:

MUMBAI: missing [2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014]
MUMBAI COMMR.: missing [2001, 2002, 2003, 2004, 2005]
MUMBAI RAILWAY: missing [2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013]
MUMBAI RLY.: missing [2014]
NAGPUR RAILWAY: missing [2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013]
NAGPUR RLY.: missing [2014]
PALGHAR: missing [2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013]
PUNE RAILWAY: missing [2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013]
PUNE RLY.: missing [2014]

======================================================================
Rows with next-year target: 581
Rows without next-year target: 50

Rows without target:

              District  Year
256             MUMBAI  2005
279        MUMBAI RLY.  2013
307        NAGPUR RLY.  2013
448          PUNE RLY.  2013
13          AHMEDNAGAR  2014
27               AKOLA  2014
41     AMRAVATI COMMR.  2014
55      AMRAVATI RURAL  2014
69   AURANGABAD COMMR.  2014
83    AURANGABAD RURAL  2014
97                BEED  2014
111           BHANDARA  2014
125           BULDHANA  2014
139         CHANDRAPUR  2014
153              DHULE  2014
167         GADCHIROLI  2014
181             GONDIA  2014
195            HINGOLI  2014
209            JALGAON  2014
223              JALNA  2014
237           KOLHAPUR  2014
251              LATUR  2014
265      MUMBAI COMMR.  2014
266     MUMBAI RAILWAY  2014
293      NAGPUR COMMR.  2014
294     NAGPUR RAILWAY  2014
321       NAGPUR RURAL  2014
335             NANDED  2014
349          NANDURBAR  2014
363       NASIK COMMR.  2014
377        NASIK RURAL  2014
391        NAVI MUMBAI  2014
405          OSMANABAD  2014
406            PALGHAR  2014
420           PARBHANI  2014
434        PUNE COMMR.  2014
435       PUNE RAILWAY  2014
462         PUNE RURAL  2014
476             RAIGAD  2014
490          RATNAGIRI  2014
504             SANGLI  2014
518             SATARA  2014
532         SINDHUDURG  2014
546     SOLAPUR COMMR.  2014
560      SOLAPUR RURAL  2014
574       THANE COMMR.  2014
588        THANE RURAL  2014
602             WARDHA  2014
616             WASHIM  2014
630           YAVATMAL  2014

In [25]:
# ============================================================
# STEP 8 — FINAL LEAKAGE-SAFE MODELING DATASET
# ============================================================

# Start from the engineered dataset
modeling_df = df.copy()

# ------------------------------------------------------------
# Keep only rows that have:
# 1. A previous-year observation
# 2. A next-year target
# ------------------------------------------------------------

required_columns = [
    "IPC_TOTAL_LAG_1",
    "WOMEN_CRIME_LAG_1",
    "VIOLENT_CRIME_LAG_1",
    "IPC_ROLLING_MEAN_3",
    "WOMEN_ROLLING_MEAN_3",
    "TARGET_NEXT_YEAR_IPC",
    "TARGET_NEXT_YEAR_WOMEN_CRIME"
]

modeling_df = modeling_df.dropna(
    subset=required_columns
).copy()


# ------------------------------------------------------------
# We cannot predict beyond 2013 because 2015 data doesn't exist
# ------------------------------------------------------------

modeling_df = modeling_df[
    modeling_df["Year"] < 2014
].copy()


# ------------------------------------------------------------
# Sort properly
# ------------------------------------------------------------

modeling_df = (
    modeling_df
    .sort_values(["Year", "District"])
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

print("=" * 70)
print("FINAL MODELING DATASET")
print("=" * 70)

print("\nShape:", modeling_df.shape)

print("\nYear coverage:")
print(
    modeling_df["Year"]
    .value_counts()
    .sort_index()
)

print("\nDistrict count:")
print(
    modeling_df["District"].nunique()
)

print("\nMissing values:")
missing = modeling_df.isna().sum()
print(missing[missing > 0])

print("\nDuplicate District-Year records:")
print(
    modeling_df.duplicated(
        subset=["District", "Year"]
    ).sum()
)

print("\nTarget statistics:")

print("\nNext-year IPC:")
print(
    modeling_df["TARGET_NEXT_YEAR_IPC"].describe()
)

print("\nNext-year women crime:")
print(
    modeling_df["TARGET_NEXT_YEAR_WOMEN_CRIME"].describe()
)

print("\nFirst 10 modeling rows:")
display(
    modeling_df[
        [
            "District",
            "Year",
            "TOTAL IPC CRIMES",
            "WOMEN_CRIME_TOTAL",
            "VIOLENT_CRIME_TOTAL",
            "PROPERTY_CRIME_TOTAL",
            "IPC_TOTAL_LAG_1",
            "IPC_ROLLING_MEAN_3",
            "TARGET_NEXT_YEAR_IPC",
            "TARGET_NEXT_YEAR_WOMEN_CRIME"
        ]
    ].head(10)
)

======================================================================
FINAL MODELING DATASET
======================================================================

Shape: (535, 45)

Year coverage:
Year
2002    45
2003    45
2004    45
2005    44
2006    44
2007    45
2008    45
2009    45
2010    45
2011    45
2012    45
2013    42
Name: count, dtype: int64

District count:
46

Missing values:
Series([], dtype: int64)

Duplicate District-Year records:
0

Target statistics:

Next-year IPC:
count      535.000000
mean      4390.900935
std       4585.020186
min        186.000000
25%       2257.500000
50%       3573.000000
75%       4709.000000
max      40361.000000
Name: TARGET_NEXT_YEAR_IPC, dtype: float64

Next-year women crime:
count     535.000000
mean      351.592523
std       306.313061
min         0.000000
25%       176.500000
50%       303.000000
75%       438.000000
max      3632.000000
Name: TARGET_NEXT_YEAR_WOMEN_CRIME, dtype: float64

First 10 modeling rows:

,District,Year,TOTAL IPC CRIMES,WOMEN_CRIME_TOTAL,VIOLENT_CRIME_TOTAL,PROPERTY_CRIME_TOTAL,IPC_TOTAL_LAG_1,IPC_ROLLING_MEAN_3,TARGET_NEXT_YEAR_IPC,TARGET_NEXT_YEAR_WOMEN_CRIME
0,AHMEDNAGAR,2002,4506,428,1261,2034,4391.0,4391.0,4251.0,413.0
1,AKOLA,2002,3886,285,1104,1772,4020.0,4020.0,3900.0,284.0
2,AMRAVATI COMMR.,2002,2665,167,650,1857,2837.0,2837.0,2986.0,182.0
3,AMRAVATI RURAL,2002,3922,336,1090,2496,3655.0,3655.0,3763.0,361.0
4,AURANGABAD COMMR.,2002,2440,180,668,1318,2351.0,2351.0,2286.0,190.0
5,AURANGABAD RURAL,2002,2703,300,1084,713,2708.0,2708.0,2675.0,296.0
6,BEED,2002,3288,253,1429,1060,3644.0,3644.0,3887.0,298.0
7,BHANDARA,2002,2258,214,582,908,2252.0,2252.0,2313.0,204.0
8,BULDHANA,2002,3665,351,1095,1715,3701.0,3701.0,3821.0,409.0
9,CHANDRAPUR,2002,2970,267,824,1191,3123.0,3123.0,3033.0,258.0

In [26]:
# ============================================================
# STEP 9 — CREATE KAGGLE-READY MODELING DATASET
# ============================================================

# Copy the validated modeling dataset
kaggle_df = modeling_df.copy()

# ------------------------------------------------------------
# Remove columns that should NOT be used as model features
# ------------------------------------------------------------

# These are identifiers or future targets.
# We keep them in a separate target section for clarity.

target_columns = [
    "TARGET_NEXT_YEAR_IPC",
    "TARGET_NEXT_YEAR_WOMEN_CRIME"
]

feature_exclude = [
    "State_UT",
    "District"
] + target_columns

feature_columns = [
    c for c in kaggle_df.columns
    if c not in feature_exclude
]

# ------------------------------------------------------------
# Create final dataset
# ------------------------------------------------------------

kaggle_modeling = kaggle_df[
    ["State_UT", "District", "Year"]
    + feature_columns
    + target_columns
].copy()

# ------------------------------------------------------------
# Final validation
# ------------------------------------------------------------

print("=" * 70)
print("KAGGLE MODELING DATASET")
print("=" * 70)

print("\nShape:", kaggle_modeling.shape)

print("\nFeature count:", len(feature_columns))

print("\nTarget columns:")
print(target_columns)

print("\nMissing values:")
missing = kaggle_modeling.isna().sum()
print(missing[missing > 0])

print("\nDuplicate District-Year records:")
print(
    kaggle_modeling
    .duplicated(["District", "Year"])
    .sum()
)

print("\nFeature columns:")
for i, col in enumerate(feature_columns, start=1):
    print(f"{i:2}. {col}")

print("\nFirst 5 rows:")
display(kaggle_modeling.head())

======================================================================
KAGGLE MODELING DATASET
======================================================================

Shape: (535, 46)

Feature count: 41

Target columns:
['TARGET_NEXT_YEAR_IPC', 'TARGET_NEXT_YEAR_WOMEN_CRIME']

Missing values:
Series([], dtype: int64)

Duplicate District-Year records:
0

Feature columns:
 1. Year
 2. MURDER
 3. ATTEMPT TO MURDER
 4. CULPABLE HOMICIDE NOT AMOUNTING TO MURDER
 5. RAPE
 6. CUSTODIAL RAPE
 7. OTHER RAPE
 8. Total Kidnapping & Abduction
 9. Kidnapping & Abduction of Women
10. Kidnapping & Abduction of Others
11. DACOITY
12. PREPARATION AND ASSEMBLY FOR DACOITY
13. ROBBERY
14. BURGLARY
15. THEFT
16. AUTO THEFT
17. OTHER THEFT
18. RIOTS
19. CRIMINAL BREACH OF TRUST
20. CHEATING
21. COUNTERFIETING
22. ARSON
23. HURT/GREVIOUS HURT
24. DOWRY DEATHS
25. ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY
26. INSULT TO MODESTY OF WOMEN
27. CRUELTY BY HUSBAND OR HIS RELATIVES
28. IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES
29. CAUSING DEATH BY NEGLIGENCE
30. OTHER IPC CRIMES
31. TOTAL IPC CRIMES
32. WOMEN_CRIME_TOTAL
33. VIOLENT_CRIME_TOTAL
34. PROPERTY_CRIME_TOTAL
35. IPC_TOTAL_LAG_1
36. WOMEN_CRIME_LAG_1
37. VIOLENT_CRIME_LAG_1
38. IPC_ROLLING_MEAN_3
39. WOMEN_ROLLING_MEAN_3
40. IPC_YEARLY_CHANGE
41. WOMEN_YEARLY_CHANGE

First 5 rows:

,State_UT,District,Year,Year,MURDER,ATTEMPT TO MURDER,CULPABLE HOMICIDE NOT AMOUNTING TO MURDER,RAPE,CUSTODIAL RAPE,OTHER RAPE,...,PROPERTY_CRIME_TOTAL,IPC_TOTAL_LAG_1,WOMEN_CRIME_LAG_1,VIOLENT_CRIME_LAG_1,IPC_ROLLING_MEAN_3,WOMEN_ROLLING_MEAN_3,IPC_YEARLY_CHANGE,WOMEN_YEARLY_CHANGE,TARGET_NEXT_YEAR_IPC,TARGET_NEXT_YEAR_WOMEN_CRIME
0,Maharashtra,AHMEDNAGAR,2002,2002,82,45,6,45,0,45,...,2034,4391.0,641.0,1165.0,4391.0,641.0,115.0,-213.0,4251.0,413.0
1,Maharashtra,AKOLA,2002,2002,59,34,0,28,0,28,...,1772,4020.0,336.0,1111.0,4020.0,336.0,-134.0,-51.0,3900.0,284.0
2,Maharashtra,AMRAVATI COMMR.,2002,2002,27,25,1,18,0,18,...,1857,2837.0,180.0,698.0,2837.0,180.0,-172.0,-13.0,2986.0,182.0
3,Maharashtra,AMRAVATI RURAL,2002,2002,58,36,3,66,0,66,...,2496,3655.0,300.0,1198.0,3655.0,300.0,267.0,36.0,3763.0,361.0
4,Maharashtra,AURANGABAD COMMR.,2002,2002,32,18,0,8,0,8,...,1318,2351.0,179.0,637.0,2351.0,179.0,89.0,1.0,2286.0,190.0

In [27]:
# ============================================================
# SAVE KAGGLE-READY DATASET
# ============================================================

kaggle_path = (
    PROCESSED_DIR /
    "maharashtra_risk_modeling_2002_2013.csv"
)

kaggle_modeling.to_csv(
    kaggle_path,
    index=False
)

print("Saved successfully:")
print(kaggle_path.resolve())

print("\nShape:", kaggle_modeling.shape)

Saved successfully:
D:\B-Tech\Project\Aditya\ml\data\processed\maharashtra_risk_modeling_2002_2013.csv

Shape: (535, 46)

In [30]:
# ============================================================
# STEP 10 — FIX DUPLICATE YEAR COLUMN
# ============================================================

# Build the final column list without duplicates
final_columns = (
    ["State_UT", "District"]
    + feature_columns
    + target_columns
)

# Remove any accidental duplicate column names
final_columns = list(dict.fromkeys(final_columns))

kaggle_modeling = kaggle_df[final_columns].copy()


# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

print("=" * 70)
print("FINAL KAGGLE DATASET")
print("=" * 70)

print("\nShape:", kaggle_modeling.shape)

print("\nDuplicate column names:")
print(
    kaggle_modeling.columns[
        kaggle_modeling.columns.duplicated()
    ].tolist()
)

print("\nMissing values:")
missing = kaggle_modeling.isna().sum()
print(missing[missing > 0])

print("\nDuplicate District-Year records:")
print(
    kaggle_modeling
    .duplicated(["District", "Year"])
    .sum()
)

print("\nColumns:")
for i, col in enumerate(kaggle_modeling.columns, 1):
    print(f"{i:2}. {col}")

print("\nFinal shape should be:")
print("535 rows × 45 columns")

======================================================================
FINAL KAGGLE DATASET
======================================================================

Shape: (535, 45)

Duplicate column names:
[]

Missing values:
Series([], dtype: int64)

Duplicate District-Year records:
0

Columns:
 1. State_UT
 2. District
 3. Year
 4. MURDER
 5. ATTEMPT TO MURDER
 6. CULPABLE HOMICIDE NOT AMOUNTING TO MURDER
 7. RAPE
 8. CUSTODIAL RAPE
 9. OTHER RAPE
10. Total Kidnapping & Abduction
11. Kidnapping & Abduction of Women
12. Kidnapping & Abduction of Others
13. DACOITY
14. PREPARATION AND ASSEMBLY FOR DACOITY
15. ROBBERY
16. BURGLARY
17. THEFT
18. AUTO THEFT
19. OTHER THEFT
20. RIOTS
21. CRIMINAL BREACH OF TRUST
22. CHEATING
23. COUNTERFIETING
24. ARSON
25. HURT/GREVIOUS HURT
26. DOWRY DEATHS
27. ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY
28. INSULT TO MODESTY OF WOMEN
29. CRUELTY BY HUSBAND OR HIS RELATIVES
30. IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES
31. CAUSING DEATH BY NEGLIGENCE
32. OTHER IPC CRIMES
33. TOTAL IPC CRIMES
34. WOMEN_CRIME_TOTAL
35. VIOLENT_CRIME_TOTAL
36. PROPERTY_CRIME_TOTAL
37. IPC_TOTAL_LAG_1
38. WOMEN_CRIME_LAG_1
39. VIOLENT_CRIME_LAG_1
40. IPC_ROLLING_MEAN_3
41. WOMEN_ROLLING_MEAN_3
42. IPC_YEARLY_CHANGE
43. WOMEN_YEARLY_CHANGE
44. TARGET_NEXT_YEAR_IPC
45. TARGET_NEXT_YEAR_WOMEN_CRIME

Final shape should be:
535 rows × 45 columns

In [31]:
# ============================================================
# SAVE FINAL KAGGLE DATASET
# ============================================================

kaggle_path = (
    PROCESSED_DIR /
    "maharashtra_risk_modeling_2002_2013.csv"
)

kaggle_modeling.to_csv(
    kaggle_path,
    index=False
)

print("Saved successfully:")
print(kaggle_path.resolve())

Saved successfully:
D:\B-Tech\Project\Aditya\ml\data\processed\maharashtra_risk_modeling_2002_2013.csv